version: '3.8'
services:
  backend: 
    build: ./backend
    image: portfolio/back
    container_name: portfolio-backend
    ports:
      - '80:80'
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env
  frontend:
      build: ./frontend
      image: portfolio/front
      container_name: portfolio-frontend
      ports:
        - '3000:3000'
      volumes:
        - ./frontend/src:/app/src #code changes are instantly reflected to running container
      stdin_open: true
      tty: true
      depends_on:
        - backend